Repository refined-github/github-url-detection, pull requests merged in 2020-06, with the labels that each got.

#9 Exclude `isConflict` from `isPR`
  index.ts
Labels: bug

#8 Automate publishing
  .github/workflows/npm-publish.yml
Labels: documentation

#12 Add `isPRCommit404` detection
  index.ts
  test.ts
Labels: enhancement

#13 Add `isRepoHome`
  index.ts
Labels: enhancement
