Repository refined-github/github-url-detection, pull requests merged in 2020-09, with the labels that each got.

#30 Automatically create release notes
  .github/workflows/publish.yml
Labels: enhancement

#33 Add `isNewRepo`
  index.ts
Labels: enhancement

#34 Add overview tab to `isUserProfileMainTab`
  index.ts
Labels: bug

#36 Add `isEmptyRepo`
  index.ts
Labels: enhancement

#35 Fix `isEmptyRepoRoot`
  index.ts
Labels: enhancement

#39 Add live demo
  .github/workflows/demo.yml
  .github/workflows/publish.yml
  demo/.gitignore
  demo/package-lock.json
  demo/package.json
  demo/public/global.css
  demo/public/index.html
  demo/rollup.config.js
  demo/src/App.svelte
  demo/src/main.ts
  demo/tsconfig.json
  package.json
  readme.md
Labels: documentation

#43 Add `isNewAction` and `isRepositoryActions`
  index.ts
Labels: enhancement
