Repository refined-github/github-url-detection, pull requests merged in 2021-05, with the labels that each got.

#73 Add `isUserSettings`
  index.ts
Labels: enhancement

#75 Include `/user/repo/labels/<label>` in `isRepoIssueList`
  index.ts
Labels: bug

#74 Convert package to pure ESM + cleanup
  .github/workflows/demo.yml
  .github/workflows/npm-publish.yml
  .gitignore
  esm/package.json
  index.ts
  package-lock.json
  package.json
  readme.md
  rollup.config.js
  test.ts
  tsconfig.json
Labels: meta

#77 Add `isPasswordConfirmation`
  index.ts
Labels: enhancement
